### ISSUE TITLE
Receive feedback from Ross and Ali

### ISSUE THREAD

**Issue by johnjasa** [mdolab/docs#5]
This is partially on installation

**Comment by johnjasa** [comment]
@shamsheersc19

**Comment by ross-chaudhry** [comment]
I am in the process of overhauling the `third party packages` page. Let me know if anybody else is working on the same page so we don't duplicate work.

**Comment by johnjasa** [comment]
@A-Gray-94 did you already provide input? If so, we can close this.

**Comment by eirikurj** [comment]
I merged his changes yesterday.... closing
